// <auto-generated />
namespace Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class REmoveParkingTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REmoveParkingTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121530113_REmove ParkingTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
